$(document).ready(function() {
  // Block#: 1
  function on_start() {
    try {
      // Block#: 2
      com.fc.JavaScriptDistLib.Label.setProperty["Text"]("labelTestResult", 'Application started event');
    } catch(e) {
      com.fc.JavaScriptDistLib.handleException(e);
    }
  };
  com.fc.JavaScriptDistLib.Application.registerEvent('start', on_start);
  $('[obj-name="MainScreen"]').show();
});
// Generated by snapp
// 471845-979472-251050-757170
